<?php
$z[0]=Array("flink","  [field:link /] </span>| <span> ",168,261);
$z[0][4]=array();
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",418,444);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",586,612);
$z[2][4]=array();
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",815,839);
$z[3][4]=array();
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",865,887);
$z[4][4]=array();
$z[4][4]['name']="cfg_add";
$z[5]=Array("global","",925,947);
$z[5][4]=array();
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",969,991);
$z[6][4]=array();
$z[6][4]['name']="cfg_fax";

?>