<?php
$z[0]=Array("global","",119,145);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",970,996);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("channel","\r\n      <li class=\"n_son\"><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n      ",1309,1552);
$z[2][4]=array();
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li class='n_son'><a href='~typelink~'>~typename~</a></li>";

?>