<?php
$z[0]=Array("type","\r\n    <h2 class=\"pnews-tl\">[field:typename/]</h2>\r\n    ",47,136);
$z[0][4]=array();
$z[0][4]['typeid']="2";
$z[1]=Array("channel","\r\n        <li class=\"pcla-son\"> <a href='[field:typeurl/]' title=\"[field:typename/]\">[field:typename/]</a> \r\n          <!--<ul>\r\n              <li><a href=\"\"></a></li>\r\n           </ul>--> \r\n        </li>\r\n        ",186,548);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="2";
$z[1][4]['currentstyle']="<li class='pcla-son'><a href='~typelink~'>~typename~</a></li>";
$z[2]=Array("type","\r\n    <h2 class=\"pnews-tl\">[field:typename/]</h2>\r\n    ",631,721);
$z[2][4]=array();
$z[2][4]['typeid']="13";
$z[3]=Array("arclist","\r\n        <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n        ",772,949);
$z[3][4]=array();
$z[3][4]['typeid']="13";
$z[3][4]['row']="5";
$z[3][4]['titlelen']="50";
$z[3][4]['orderby']="pubdate";
$z[4]=Array("type","\r\n    <h2 class=\"pcontact-tl\">[field:typename/]</h2>\r\n    ",1036,1129);
$z[4][4]=array();
$z[4][4]['typeid']="12";
$z[5]=Array("global","",1221,1243);
$z[5][4]=array();
$z[5][4]['name']="cfg_add";
$z[6]=Array("global","",1317,1339);
$z[6][4]=array();
$z[6][4]['name']="cfg_tel";
$z[7]=Array("global","",1413,1435);
$z[7][4]=array();
$z[7][4]['name']="cfg_fax";
$z[8]=Array("global","",1509,1533);
$z[8][4]=array();
$z[8][4]['name']="cfg_email";

?>